apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-traffic-from-my-ip
  # allow traffic from your system's IP to the ALB IP address and port
spec:
  applyOnForward: true
  preDNAT: true
  ingress:
  - action: Allow
    destination:
      nets:
      # IPs Ingress subdomain from cfee3-eu-demo cluster
      # dig cfee3-eu-demo-cluster.eu-de.containers.appdomain.cloud
      - 158.177.180.90/32
      - 161.156.120.78/32
      ports:
      - 80
      - 443
    protocol: TCP
    source:
      nets:
      - 78.207.202.120/32
      ports:
      - 80
      - 443
  selector: ibm.role =='worker_public'
  order: 500
  types:
  - Ingress
