apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  # Deny all incoming TCP traffic from any source IP to the ALB IP address and port
  name: deny-alb-traffic
spec:
  applyOnForward: true
  preDNAT: true
  ingress:
  - action: Deny
    destination:
      nets:
      # IPs of (ALB) Automatic Load Balancer (a.k.a Ingress)
      # CLI: kubectl get ingress
      - 169.50.19.214/32
      - 161.156.130.142/32
      - 149.81.67.38/32
      ports:
      - 80
      - 443
    protocol: TCP
    source: {}
  selector: ibm.role == 'worker_public'
  order: 4000
  types:
  - Ingress